loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_org_plugin:
  repo:         loomio/loomio_org_plugin

loomio_tags:
  repo:         loomio/loomio_tags
  experimental: true

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true

loomio_group_progress_card:
  repo: loomio/loomio_group_progress_card
  experimental: true
